name: Package addon

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

concurrency:
  group: packager

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -q

      - name: Package and release
        uses: BigWigsMods/packager@master
        if: always()
